{
  products{
    _id
    title
    imageURL
    short_text
    text
    tags
    dislikes {
      _id
      first_name
    }
    likes {
      first_name
    }
    supplier {
      first_name
      last_name
    }
    comments{
      _id
      comment
      user {
        first_name
        last_name
      }
    }
    category {
      title
      _id
    }
    feture {
      height
      width
      weight
      colors
      length
    }
  }
}